[package]
name = "gabe_channels"
version = "0.1.0"
edition = "2021"

[dependencies]


[features]
application = []
device = []
network = ["rustls"]
default = ["application", "device", "network"]

[dependencies.rustls]
version = "0.23.22"
optional = true
